/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * BackendStory API
 * API для управления перечислениями, пользователями и аутентификацией
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePersonRequest,
  DeletePersonsIdParams,
  EnumCreateRequest,
  EnumDTO,
  EnumValueCreateRequest,
  EnumValueDTO,
  ErrorResponse,
  GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody,
  Jwt,
  LoginRequest,
  PersonDTO,
  RegisterUserRequest,
  TokenRequest,
  TokenUserInfo,
  UserDTO
} from './api.schemas';

import { customInstance } from '../config/axios';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает список всех доступных ролей в системе
 * @summary Получить все роли
 */
export const getAuthRoles = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/auth/roles`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthRolesQueryKey = () => {
    return [
    `/auth/roles`
    ] as const;
    }

    
export const getGetAuthRolesQueryOptions = <TData = Awaited<ReturnType<typeof getAuthRoles>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthRoles>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthRolesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthRoles>>> = ({ signal }) => getAuthRoles(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthRoles>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthRoles>>>
export type GetAuthRolesQueryError = ErrorResponse


/**
 * @summary Получить все роли
 */

export function useGetAuthRoles<TData = Awaited<ReturnType<typeof getAuthRoles>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthRoles>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthRolesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Возвращает информацию из текущего токена
 * @summary Получить информацию из текущего токена
 */
export const getAuthToken = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenUserInfo>(
      {url: `/auth/token`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthTokenQueryKey = () => {
    return [
    `/auth/token`
    ] as const;
    }

    
export const getGetAuthTokenQueryOptions = <TData = Awaited<ReturnType<typeof getAuthToken>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthToken>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthTokenQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthToken>>> = ({ signal }) => getAuthToken(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthToken>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthToken>>>
export type GetAuthTokenQueryError = ErrorResponse


/**
 * @summary Получить информацию из текущего токена
 */

export function useGetAuthToken<TData = Awaited<ReturnType<typeof getAuthToken>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthToken>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthTokenQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Возвращает информацию из токена
 * @summary Получить информацию из токена
 */
export const postAuthToken = (
    tokenRequest: TokenRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenUserInfo>(
      {url: `/auth/token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRequest, signal
    },
      options);
    }
  


export const getPostAuthTokenMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthToken>>, TError,{data: TokenRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthToken>>, TError,{data: TokenRequest}, TContext> => {

const mutationKey = ['postAuthToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthToken>>, {data: TokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthToken>>>
    export type PostAuthTokenMutationBody = TokenRequest
    export type PostAuthTokenMutationError = ErrorResponse

    /**
 * @summary Получить информацию из токена
 */
export const usePostAuthToken = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthToken>>, TError,{data: TokenRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthToken>>,
        TError,
        {data: TokenRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает список всех зарегистрированных пользователей
 * @summary Получить всех пользователей
 */
export const getAuthUsers = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserDTO[]>(
      {url: `/auth/users`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthUsersQueryKey = () => {
    return [
    `/auth/users`
    ] as const;
    }

    
export const getGetAuthUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAuthUsers>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthUsers>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthUsers>>> = ({ signal }) => getAuthUsers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthUsers>>>
export type GetAuthUsersQueryError = ErrorResponse


/**
 * @summary Получить всех пользователей
 */

export function useGetAuthUsers<TData = Awaited<ReturnType<typeof getAuthUsers>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthUsers>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthUsersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Возвращает пользователя по username
 * @summary Получить пользователя
 */
export const getAuthUsersUsername = (
    username: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserDTO>(
      {url: `/auth/users/${username}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthUsersUsernameQueryKey = (username?: string,) => {
    return [
    `/auth/users/${username}`
    ] as const;
    }

    
export const getGetAuthUsersUsernameQueryOptions = <TData = Awaited<ReturnType<typeof getAuthUsersUsername>>, TError = ErrorResponse>(username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthUsersUsername>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthUsersUsernameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthUsersUsername>>> = ({ signal }) => getAuthUsersUsername(username, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthUsersUsername>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthUsersUsernameQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthUsersUsername>>>
export type GetAuthUsersUsernameQueryError = ErrorResponse


/**
 * @summary Получить пользователя
 */

export function useGetAuthUsersUsername<TData = Awaited<ReturnType<typeof getAuthUsersUsername>>, TError = ErrorResponse>(
 username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthUsersUsername>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthUsersUsernameQueryOptions(username,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Возвращает список ролей для указанного пользователя
 * @summary Получить роли пользователя
 */
export const getAuthUsersUsernameRoles = (
    username: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/auth/users/${username}/roles`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthUsersUsernameRolesQueryKey = (username?: string,) => {
    return [
    `/auth/users/${username}/roles`
    ] as const;
    }

    
export const getGetAuthUsersUsernameRolesQueryOptions = <TData = Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>, TError = ErrorResponse>(username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthUsersUsernameRolesQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>> = ({ signal }) => getAuthUsersUsernameRoles(username, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthUsersUsernameRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>>
export type GetAuthUsersUsernameRolesQueryError = ErrorResponse


/**
 * @summary Получить роли пользователя
 */

export function useGetAuthUsersUsernameRoles<TData = Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>, TError = ErrorResponse>(
 username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthUsersUsernameRoles>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthUsersUsernameRolesQueryOptions(username,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Возвращает список всех значений перечислений
 * @summary Получить все значения перечислений
 */
export const getEnumerationValues = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumValueDTO[]>(
      {url: `/enumeration-values`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumerationValuesQueryKey = () => {
    return [
    `/enumeration-values`
    ] as const;
    }

    
export const getGetEnumerationValuesQueryOptions = <TData = Awaited<ReturnType<typeof getEnumerationValues>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValues>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumerationValuesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumerationValues>>> = ({ signal }) => getEnumerationValues(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValues>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumerationValuesQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumerationValues>>>
export type GetEnumerationValuesQueryError = ErrorResponse


/**
 * @summary Получить все значения перечислений
 */

export function useGetEnumerationValues<TData = Awaited<ReturnType<typeof getEnumerationValues>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValues>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumerationValuesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Создает новое значение перечисления
 * @summary Создать значение перечисления
 */
export const postEnumerationValues = (
    enumValueCreateRequest: EnumValueCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumValueDTO>(
      {url: `/enumeration-values`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enumValueCreateRequest, signal
    },
      options);
    }
  


export const getPostEnumerationValuesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerationValues>>, TError,{data: EnumValueCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postEnumerationValues>>, TError,{data: EnumValueCreateRequest}, TContext> => {

const mutationKey = ['postEnumerationValues'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEnumerationValues>>, {data: EnumValueCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postEnumerationValues(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostEnumerationValuesMutationResult = NonNullable<Awaited<ReturnType<typeof postEnumerationValues>>>
    export type PostEnumerationValuesMutationBody = EnumValueCreateRequest
    export type PostEnumerationValuesMutationError = ErrorResponse

    /**
 * @summary Создать значение перечисления
 */
export const usePostEnumerationValues = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerationValues>>, TError,{data: EnumValueCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postEnumerationValues>>,
        TError,
        {data: EnumValueCreateRequest},
        TContext
      > => {

      const mutationOptions = getPostEnumerationValuesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает все значения для указанного перечисления
 * @summary Получить значения по ID перечисления
 */
export const getEnumerationValuesEnumerationEnumerationId = (
    enumerationId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumValueDTO[]>(
      {url: `/enumeration-values/enumeration/${enumerationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumerationValuesEnumerationEnumerationIdQueryKey = (enumerationId?: number,) => {
    return [
    `/enumeration-values/enumeration/${enumerationId}`
    ] as const;
    }

    
export const getGetEnumerationValuesEnumerationEnumerationIdQueryOptions = <TData = Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>, TError = ErrorResponse>(enumerationId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumerationValuesEnumerationEnumerationIdQueryKey(enumerationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>> = ({ signal }) => getEnumerationValuesEnumerationEnumerationId(enumerationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(enumerationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumerationValuesEnumerationEnumerationIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>>
export type GetEnumerationValuesEnumerationEnumerationIdQueryError = ErrorResponse


/**
 * @summary Получить значения по ID перечисления
 */

export function useGetEnumerationValuesEnumerationEnumerationId<TData = Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>, TError = ErrorResponse>(
 enumerationId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValuesEnumerationEnumerationId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumerationValuesEnumerationEnumerationIdQueryOptions(enumerationId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Выполняет поиск значений перечислений по заданным критериям
 * @summary Поиск значений перечислений
 */
export const postEnumerationValuesSearch = (
    githubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumValueDTO[]>(
      {url: `/enumeration-values/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: githubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody, signal
    },
      options);
    }
  


export const getPostEnumerationValuesSearchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerationValuesSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postEnumerationValuesSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext> => {

const mutationKey = ['postEnumerationValuesSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEnumerationValuesSearch>>, {data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}> = (props) => {
          const {data} = props ?? {};

          return  postEnumerationValuesSearch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostEnumerationValuesSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postEnumerationValuesSearch>>>
    export type PostEnumerationValuesSearchMutationBody = GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody
    export type PostEnumerationValuesSearchMutationError = ErrorResponse

    /**
 * @summary Поиск значений перечислений
 */
export const usePostEnumerationValuesSearch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerationValuesSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postEnumerationValuesSearch>>,
        TError,
        {data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody},
        TContext
      > => {

      const mutationOptions = getPostEnumerationValuesSearchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает значение перечисления по указанному идентификатору
 * @summary Получить значение перечисления по ID
 */
export const getEnumerationValuesId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumValueDTO>(
      {url: `/enumeration-values/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumerationValuesIdQueryKey = (id?: number,) => {
    return [
    `/enumeration-values/${id}`
    ] as const;
    }

    
export const getGetEnumerationValuesIdQueryOptions = <TData = Awaited<ReturnType<typeof getEnumerationValuesId>>, TError = ErrorResponse>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValuesId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumerationValuesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumerationValuesId>>> = ({ signal }) => getEnumerationValuesId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValuesId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumerationValuesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumerationValuesId>>>
export type GetEnumerationValuesIdQueryError = ErrorResponse


/**
 * @summary Получить значение перечисления по ID
 */

export function useGetEnumerationValuesId<TData = Awaited<ReturnType<typeof getEnumerationValuesId>>, TError = ErrorResponse>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationValuesId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumerationValuesIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Удаляет значение перечисления по указанному идентификатору
 * @summary Удалить значение перечисления
 */
export const deleteEnumerationValuesId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/enumeration-values/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteEnumerationValuesIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEnumerationValuesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEnumerationValuesId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteEnumerationValuesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEnumerationValuesId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteEnumerationValuesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEnumerationValuesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEnumerationValuesId>>>
    
    export type DeleteEnumerationValuesIdMutationError = ErrorResponse

    /**
 * @summary Удалить значение перечисления
 */
export const useDeleteEnumerationValuesId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEnumerationValuesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteEnumerationValuesId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteEnumerationValuesIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает список всех перечислений в системе
 * @summary Получить все перечисления
 */
export const getEnumerations = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumDTO[]>(
      {url: `/enumerations`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumerationsQueryKey = () => {
    return [
    `/enumerations`
    ] as const;
    }

    
export const getGetEnumerationsQueryOptions = <TData = Awaited<ReturnType<typeof getEnumerations>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerations>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumerationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumerations>>> = ({ signal }) => getEnumerations(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumerations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumerationsQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumerations>>>
export type GetEnumerationsQueryError = ErrorResponse


/**
 * @summary Получить все перечисления
 */

export function useGetEnumerations<TData = Awaited<ReturnType<typeof getEnumerations>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerations>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumerationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Создает новое перечисление в системе
 * @summary Создать перечисление
 */
export const postEnumerations = (
    enumCreateRequest: EnumCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumDTO>(
      {url: `/enumerations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: enumCreateRequest, signal
    },
      options);
    }
  


export const getPostEnumerationsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerations>>, TError,{data: EnumCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postEnumerations>>, TError,{data: EnumCreateRequest}, TContext> => {

const mutationKey = ['postEnumerations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEnumerations>>, {data: EnumCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postEnumerations(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostEnumerationsMutationResult = NonNullable<Awaited<ReturnType<typeof postEnumerations>>>
    export type PostEnumerationsMutationBody = EnumCreateRequest
    export type PostEnumerationsMutationError = ErrorResponse

    /**
 * @summary Создать перечисление
 */
export const usePostEnumerations = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerations>>, TError,{data: EnumCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postEnumerations>>,
        TError,
        {data: EnumCreateRequest},
        TContext
      > => {

      const mutationOptions = getPostEnumerationsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает перечисление по указанному коду
 * @summary Получить перечисление по коду
 */
export const getEnumerationsCodeCode = (
    code: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumDTO>(
      {url: `/enumerations/code/${code}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumerationsCodeCodeQueryKey = (code?: string,) => {
    return [
    `/enumerations/code/${code}`
    ] as const;
    }

    
export const getGetEnumerationsCodeCodeQueryOptions = <TData = Awaited<ReturnType<typeof getEnumerationsCodeCode>>, TError = ErrorResponse>(code: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationsCodeCode>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumerationsCodeCodeQueryKey(code);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumerationsCodeCode>>> = ({ signal }) => getEnumerationsCodeCode(code, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(code), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumerationsCodeCode>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumerationsCodeCodeQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumerationsCodeCode>>>
export type GetEnumerationsCodeCodeQueryError = ErrorResponse


/**
 * @summary Получить перечисление по коду
 */

export function useGetEnumerationsCodeCode<TData = Awaited<ReturnType<typeof getEnumerationsCodeCode>>, TError = ErrorResponse>(
 code: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationsCodeCode>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumerationsCodeCodeQueryOptions(code,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Выполняет поиск перечислений по заданным критериям
 * @summary Поиск перечислений
 */
export const postEnumerationsSearch = (
    githubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumDTO[]>(
      {url: `/enumerations/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: githubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody, signal
    },
      options);
    }
  


export const getPostEnumerationsSearchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerationsSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postEnumerationsSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext> => {

const mutationKey = ['postEnumerationsSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEnumerationsSearch>>, {data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}> = (props) => {
          const {data} = props ?? {};

          return  postEnumerationsSearch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostEnumerationsSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postEnumerationsSearch>>>
    export type PostEnumerationsSearchMutationBody = GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody
    export type PostEnumerationsSearchMutationError = ErrorResponse

    /**
 * @summary Поиск перечислений
 */
export const usePostEnumerationsSearch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnumerationsSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postEnumerationsSearch>>,
        TError,
        {data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody},
        TContext
      > => {

      const mutationOptions = getPostEnumerationsSearchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает перечисление по указанному идентификатору
 * @summary Получить перечисление по ID
 */
export const getEnumerationsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumDTO>(
      {url: `/enumerations/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumerationsIdQueryKey = (id?: number,) => {
    return [
    `/enumerations/${id}`
    ] as const;
    }

    
export const getGetEnumerationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getEnumerationsId>>, TError = ErrorResponse>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationsId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumerationsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumerationsId>>> = ({ signal }) => getEnumerationsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumerationsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumerationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumerationsId>>>
export type GetEnumerationsIdQueryError = ErrorResponse


/**
 * @summary Получить перечисление по ID
 */

export function useGetEnumerationsId<TData = Awaited<ReturnType<typeof getEnumerationsId>>, TError = ErrorResponse>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumerationsId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumerationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Удаляет перечисление по указанному идентификатору
 * @summary Удалить перечисление
 */
export const deleteEnumerationsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/enumerations/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteEnumerationsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEnumerationsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEnumerationsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteEnumerationsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEnumerationsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteEnumerationsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEnumerationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEnumerationsId>>>
    
    export type DeleteEnumerationsIdMutationError = ErrorResponse

    /**
 * @summary Удалить перечисление
 */
export const useDeleteEnumerationsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEnumerationsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteEnumerationsId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteEnumerationsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Выполняет вход пользователя и возвращает токен
 * @summary Аутентификация пользователя
 */
export const postLogin = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Jwt>(
      {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getPostLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['postLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
    export type PostLoginMutationBody = LoginRequest
    export type PostLoginMutationError = ErrorResponse

    /**
 * @summary Аутентификация пользователя
 */
export const usePostLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getPostLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает список всех персон в системе
 * @summary Получить всех персон
 */
export const getPersons = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PersonDTO[]>(
      {url: `/persons`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPersonsQueryKey = () => {
    return [
    `/persons`
    ] as const;
    }

    
export const getGetPersonsQueryOptions = <TData = Awaited<ReturnType<typeof getPersons>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPersons>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPersonsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersons>>> = ({ signal }) => getPersons(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPersons>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPersonsQueryResult = NonNullable<Awaited<ReturnType<typeof getPersons>>>
export type GetPersonsQueryError = ErrorResponse


/**
 * @summary Получить всех персон
 */

export function useGetPersons<TData = Awaited<ReturnType<typeof getPersons>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPersons>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPersonsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Создает новую персону в системе
 * @summary Создать персону
 */
export const postPersons = (
    createPersonRequest: CreatePersonRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PersonDTO>(
      {url: `/persons`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPersonRequest, signal
    },
      options);
    }
  


export const getPostPersonsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPersons>>, TError,{data: CreatePersonRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postPersons>>, TError,{data: CreatePersonRequest}, TContext> => {

const mutationKey = ['postPersons'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPersons>>, {data: CreatePersonRequest}> = (props) => {
          const {data} = props ?? {};

          return  postPersons(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPersonsMutationResult = NonNullable<Awaited<ReturnType<typeof postPersons>>>
    export type PostPersonsMutationBody = CreatePersonRequest
    export type PostPersonsMutationError = ErrorResponse

    /**
 * @summary Создать персону
 */
export const usePostPersons = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPersons>>, TError,{data: CreatePersonRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPersons>>,
        TError,
        {data: CreatePersonRequest},
        TContext
      > => {

      const mutationOptions = getPostPersonsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Выполняет поиск людей по заданным критериям
 * @summary Поиск людей
 */
export const postPersonsSearch = (
    githubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PersonDTO[]>(
      {url: `/persons/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: githubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody, signal
    },
      options);
    }
  


export const getPostPersonsSearchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPersonsSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postPersonsSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext> => {

const mutationKey = ['postPersonsSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPersonsSearch>>, {data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}> = (props) => {
          const {data} = props ?? {};

          return  postPersonsSearch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPersonsSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postPersonsSearch>>>
    export type PostPersonsSearchMutationBody = GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody
    export type PostPersonsSearchMutationError = ErrorResponse

    /**
 * @summary Поиск людей
 */
export const usePostPersonsSearch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPersonsSearch>>, TError,{data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPersonsSearch>>,
        TError,
        {data: GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody},
        TContext
      > => {

      const mutationOptions = getPostPersonsSearchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Возвращает персону по указанному логину пользователя
 * @summary Получить персону по логину пользователя
 */
export const getPersonsUserUserLogin = (
    userLogin: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PersonDTO>(
      {url: `/persons/user/${userLogin}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPersonsUserUserLoginQueryKey = (userLogin?: string,) => {
    return [
    `/persons/user/${userLogin}`
    ] as const;
    }

    
export const getGetPersonsUserUserLoginQueryOptions = <TData = Awaited<ReturnType<typeof getPersonsUserUserLogin>>, TError = ErrorResponse>(userLogin: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPersonsUserUserLogin>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPersonsUserUserLoginQueryKey(userLogin);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonsUserUserLogin>>> = ({ signal }) => getPersonsUserUserLogin(userLogin, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userLogin), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPersonsUserUserLogin>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPersonsUserUserLoginQueryResult = NonNullable<Awaited<ReturnType<typeof getPersonsUserUserLogin>>>
export type GetPersonsUserUserLoginQueryError = ErrorResponse


/**
 * @summary Получить персону по логину пользователя
 */

export function useGetPersonsUserUserLogin<TData = Awaited<ReturnType<typeof getPersonsUserUserLogin>>, TError = ErrorResponse>(
 userLogin: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPersonsUserUserLogin>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPersonsUserUserLoginQueryOptions(userLogin,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Возвращает персону по указанному идентификатору
 * @summary Получить персону по ID
 */
export const getPersonsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PersonDTO>(
      {url: `/persons/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPersonsIdQueryKey = (id?: number,) => {
    return [
    `/persons/${id}`
    ] as const;
    }

    
export const getGetPersonsIdQueryOptions = <TData = Awaited<ReturnType<typeof getPersonsId>>, TError = ErrorResponse>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPersonsId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPersonsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonsId>>> = ({ signal }) => getPersonsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPersonsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPersonsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPersonsId>>>
export type GetPersonsIdQueryError = ErrorResponse


/**
 * @summary Получить персону по ID
 */

export function useGetPersonsId<TData = Awaited<ReturnType<typeof getPersonsId>>, TError = ErrorResponse>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPersonsId>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPersonsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Удаляет персону по указанному идентификатору. Поддерживает мягкое удаление (soft delete)
 * @summary Удалить персону
 */
export const deletePersonsId = (
    id: number,
    params?: DeletePersonsIdParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/persons/${id}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeletePersonsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePersonsId>>, TError,{id: number;params?: DeletePersonsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePersonsId>>, TError,{id: number;params?: DeletePersonsIdParams}, TContext> => {

const mutationKey = ['deletePersonsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePersonsId>>, {id: number;params?: DeletePersonsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  deletePersonsId(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePersonsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deletePersonsId>>>
    
    export type DeletePersonsIdMutationError = ErrorResponse

    /**
 * @summary Удалить персону
 */
export const useDeletePersonsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePersonsId>>, TError,{id: number;params?: DeletePersonsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePersonsId>>,
        TError,
        {id: number;params?: DeletePersonsIdParams},
        TContext
      > => {

      const mutationOptions = getDeletePersonsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Создает нового пользователя и возвращает токен
 * @summary Регистрация пользователя
 */
export const postRegister = (
    registerUserRequest: RegisterUserRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Jwt>(
      {url: `/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerUserRequest, signal
    },
      options);
    }
  


export const getPostRegisterMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: RegisterUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: RegisterUserRequest}, TContext> => {

const mutationKey = ['postRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRegister>>, {data: RegisterUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postRegister>>>
    export type PostRegisterMutationBody = RegisterUserRequest
    export type PostRegisterMutationError = ErrorResponse

    /**
 * @summary Регистрация пользователя
 */
export const usePostRegister = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: RegisterUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postRegister>>,
        TError,
        {data: RegisterUserRequest},
        TContext
      > => {

      const mutationOptions = getPostRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
