/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * BackendStory API
 * API для управления перечислениями, пользователями и аутентификацией
 * OpenAPI spec version: 1.0
 */
export interface ErrorResponse {
  code?: string;
  message?: string;
  method?: string;
  path?: string;
  status?: number;
  timestamp?: string;
}

export type Operator = typeof Operator[keyof typeof Operator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Operator = {
  OpEqual: '=',
  OpNotEqual: '!=',
  OpGreater: '>',
  OpGreaterEq: '>=',
  OpLess: '<',
  OpLessEq: '<=',
  OpIn: 'in',
  OpLike: 'like',
} as const;

export interface SearchCondition {
  field: string;
  operation: Operator;
  value: unknown;
}

export interface SearchCriteria {
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset?: number;
  /**
   * @minLength 1
   * @maxLength 50
   */
  order_by?: string;
  search_conditions?: SearchCondition[];
}

export interface Jwt {
  access_token?: string;
  expires_in?: number;
  refresh_expires_in?: number;
  refresh_token?: string;
}

export interface LoginRequest {
  /** could be username or email */
  login: string;
  password: string;
}

export interface LoginResponse {
  roles?: string[];
  token?: Jwt;
  username?: string;
}

export interface RegisterUserRequest {
  confirm_password: string;
  email: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  password: string;
  username: string;
}

export interface TokenRequest {
  token: string;
}

export interface TokenUserInfo {
  email?: string;
  roles?: string[];
  username?: string;
}

export interface UserDTO {
  created_at?: string;
  email?: string;
  id?: string;
  username?: string;
}

export interface CartCreateRequest {
  /** @minimum 1 */
  person_id: number;
}

export interface CartDTO {
  created_at?: string;
  id: number;
  person_id: number;
  updated_at?: string;
}

export interface CartItemCreateRequest {
  /** @minimum 1 */
  cart_id: number;
  /** @minimum 1 */
  product_id: number;
  /** @minimum 1 */
  quantity: number;
}

export interface CartItemDTO {
  cart_id: number;
  created_at?: string;
  id: number;
  product_id: number;
  quantity: number;
  updated_at?: string;
}

export interface CategoryCreateRequest {
  /** @minimum 1 */
  category_id?: number;
  /**
   * @minLength 1
   * @maxLength 50
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  label: string;
}

export interface CategoryDTO {
  category_id: number;
  code: string;
  created_at?: string;
  id: number;
  label: string;
  updated_at?: string;
}

export interface EnumCreateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  label: string;
}

export interface EnumDTO {
  code: string;
  created_at?: string;
  id: number;
  label: string;
  updated_at?: string;
}

export interface EnumValueCreateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  code: string;
  enumeration_id: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  label: string;
}

export interface EnumValueDTO {
  code: string;
  created_at?: string;
  enum_id: number;
  id: number;
  label: string;
  updated_at?: string;
}

export interface CreatePersonRequest {
  /**
   * @minLength 2
   * @maxLength 50
   */
  firstname: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  lastname: string;
  phone: string;
  user_login: string;
}

export interface PersonDTO {
  created_at?: string;
  deleted_at?: string;
  firstname: string;
  id: number;
  lastname: string;
  phone: string;
  updated_at?: string;
  user_login: string;
}

export interface ProductCreateRequest {
  /** @minimum 1 */
  category_id: number;
  /**
   * @minLength 1
   * @maxLength 50
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  label: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  price: string;
  /** @minimum 0 */
  quantity: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  sku: string;
  status_id: number;
}

export interface ProductDTO {
  category_id: number;
  code: string;
  created_at?: string;
  id: number;
  label: string;
  price: string;
  quantity: number;
  sku: string;
  status_id: number;
  updated_at?: string;
}

/**
 * Product media information
 */
export interface ProductMediaDTO {
  created_at?: string;
  id: number;
  link?: string;
  product_id: number;
  updated_at?: string;
}

export interface AddToCartRequest {
  /** @minimum 1 */
  product_id: number;
  /** @minimum 1 */
  quantity: number;
}

export interface PurchaseRequest {
  /** @minimum 1 */
  cart_id: number;
}

/**
 * Критерии поиска
 */
export type GithubComActuallyHelloBackendstoryPkgCoreSearchCriteriaBody = SearchCriteria;

/**
 * Данные для создания элемента корзины
 */
export type PkgBackendstoryCartItemCartItemCreateRequestBody = CartItemCreateRequest;

export type DeletePersonParams = {
/**
 * Флаг мягкого удаления (true/false)
 */
soft?: boolean;
};

export type UploadProductMediaImageBody = {
  /**
   * ID товара
   * @minimum 1
   */
  product_id: number;
  /** Изображение товара */
  file: Blob;
};

