/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * BackendStory API
 * API для управления перечислениями, пользователями и аутентификацией
 * OpenAPI spec version: 1.0
 */
export interface CreatePersonRequest {
  /**
   * @minLength 2
   * @maxLength 50
   */
  firstname: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  lastname: string;
  phone: string;
  user_login: string;
}

export interface EnumCreateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  label: string;
}

export interface EnumDTO {
  code?: string;
  id?: number;
  label?: string;
}

export interface EnumValueCreateRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  code: string;
  enumeration_id: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  label: string;
}

export interface EnumValueDTO {
  code?: string;
  enum_id?: number;
  id?: number;
  label?: string;
}

export interface ErrorResponse {
  code?: string;
  message?: string;
  method?: string;
  path?: string;
  status?: number;
  timestamp?: string;
}

export interface Jwt {
  access_token?: string;
  expires_in?: number;
  refresh_expires_in?: number;
  refresh_token?: string;
}

export interface LoginRequest {
  /** could be username or email */
  login: string;
  password: string;
}

export type Operator = typeof Operator[keyof typeof Operator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Operator = {
  OpEqual: '=',
  OpNotEqual: '!=',
  OpGreater: '>',
  OpGreaterEq: '>=',
  OpLess: '<',
  OpLessEq: '<=',
  OpIn: 'in',
  OpLike: 'like',
} as const;

export interface PersonDTO {
  created_at?: string;
  deleted_at?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
  phone?: string;
  updated_at?: string;
  user_login?: string;
}

export interface RegisterUserRequest {
  confirm_password: string;
  email: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  password: string;
  username: string;
}

export interface SearchCondition {
  field: string;
  operation: Operator;
  value: unknown;
}

export interface SearchCriteria {
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset?: number;
  order_by?: string;
  search_conditions?: SearchCondition[];
}

export interface TokenRequest {
  token: string;
}

export interface TokenUserInfo {
  email?: string;
  roles?: string[];
  username?: string;
}

export interface UserDTO {
  created_at?: string;
  email?: string;
  id?: string;
  username?: string;
}

/**
 * Критерии поиска
 */
export type GithubComActuallyHelloBackendstoryInternalDtoSearchCriteriaBody = SearchCriteria;

export type DeletePersonsIdParams = {
/**
 * Флаг мягкого удаления (true/false)
 */
soft?: boolean;
};

